# Generated by Django 6.0.7 on 2026-07-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAdvisory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('raw_payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'source_advisories',
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
