# Generated by Django 6.0.7 on 2026-07-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_auto_20260717_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, help_text='Feeder source identifier (e.g., nvd, ghsa, osv, aws, docker_ecosystem, docker_hardened_osv)', max_length=50)),
                ('last_successful_sync', models.DateTimeField(blank=True, help_text='UTC timestamp used as the delta baseline for this specific sync cycle', null=True)),
                ('last_run_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', help_text='Execution outcome of this job run (SUCCESS, FAILED, or RUNNING)', max_length=20)),
                ('records_processed', models.IntegerField(default=0, help_text='Number of records inserted or updated during this specific run cycle')),
                ('error_message', models.TextField(default='No error occurred', help_text='Diagnostic exception string or failure stack trace if job failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this job execution entry was recorded')),
            ],
            options={
                'db_table': 'ingestion_sync_state',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'last_run_status', '-created_at'], name='idx_syncstate_lookup')],
            },
        ),
    ]
