# Generated by Django 6.0.7 on 2026-07-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_seed_initial_sync_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncstate',
            name='error_message',
            field=models.TextField(blank=True, help_text='Diagnostic exception string or failure stack trace if job failed', null=True),
        ),
        migrations.AlterField(
            model_name='syncstate',
            name='last_run_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Execution state of this job run (PENDING, RUNNING, SUCCESS, FAILED)', max_length=20),
        ),
        migrations.AlterField(
            model_name='syncstate',
            name='source',
            field=models.CharField(db_index=True, help_text='Feeder source identifier (e.g., nvd, ghsa, osv, aws, docker_ecosystem)', max_length=50),
        ),
    ]
