# Generated by Django 6.0.7 on 2026-07-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_alter_syncstate_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceadvisory',
            name='normalized_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
