# Generated by Django 6.0.7 on 2026-07-29 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0009_alter_vulnerabilitytag_ecosystem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualRemediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('guidance_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_vuln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediations', to='ingestion.mastervulnerability')),
            ],
            options={
                'db_table': 'manual_remediations',
                'ordering': ['-created_at'],
            },
        ),
    ]
