# Generated by Django 6.0.7 on 2026-08-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0011_mastervulnerability_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualremediation',
            name='author_name',
        ),
        migrations.AddField(
            model_name='manualremediation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manualremediation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manual_remediations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RemediationVote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vote_type', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ingestion.manualremediation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remediation_votes',
                'indexes': [models.Index(fields=['remediation', 'vote_type'], name='remediation_remedia_87feb5_idx')],
                'constraints': [models.UniqueConstraint(fields=('remediation', 'user'), name='uq_one_vote_per_user_per_remediation')],
            },
        ),
    ]
